server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.2.100:3306/zmall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.fred.mall.option.model.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true


